### ISSUE TITLE
Reduce shadow size of top and side bar.

### ISSUE THREAD

**Issue by theXYZT** [axyjo/drts_ruby#47]

**Comment by axyjo** [comment]
At least make them consistent. Apparently, one of them is 20px, while the other is only 10px.

**Comment by axyjo** [comment]
Can't close this yet until we get FF sorted out since it's one of our top-tier browsers. I couldn't have cared less if it was IE < 8, but we need to keep FF support active.

**Comment by theXYZT** [comment]
http://dl.dropbox.com/u/113663/wtfdifference.png

Dotcloud and Localhost editions work identically on Canary. But differently on Firefox. I pulled right before testing, so the assumption is that the code is the same.

Any idea what could cause the same code to display different webpages?

**Comment by axyjo** [comment]
Possibly http://forums.mozillazine.org/viewtopic.php?p=10935695#p10935695 but @nikhilm92 countered with saying that if it was indeed a FF bug, then it would be rendered the same, but incorrect on both hosts.

**Comment by theXYZT** [comment]
For unknown reasons, the FF bug still exists.
http://dl.dropbox.com/u/113663/wtf2.png
LOCALHOST renders the page perfectly (The navbar height is exactly as specified in the CSS file).
DOTCLOUD renders the page incorrectly (The havbar height is 3 pixels less than specified in CSS).

Still trying to figure out why dotcloud is messing things up, when the same code is working well on localhost.

@axyjo, Could you take screenshots the way I did too and tell me if the problem exists for you too?

**Comment by axyjo** [comment]
Related commit: 6ca3a01e247063771b97

@nikhilm92: Triggering "javascript:alert(Game.navbar.height());" on both Chrome stable and Firefox 5 on Dotcloud returns "29". Try clearing your cache?

My results: http://i.imgur.com/r5Kzr.png

**Comment by axyjo** [comment]
@nikhilm92's friends get 29 px as well. Time to close this?

**Comment by axyjo** [comment]
@nikhilm92 had bad zooming on his Firefox. Issue closed.
