### ISSUE TITLE
Remove extra zoom level.

### ISSUE THREAD

**Issue by theXYZT** [axyjo/drts_ruby#65]
Reasons:
1. Unnecessary.
2. Pixelation.
3. Ugly.

**Comment by axyjo** [comment]
2 and 3 are the same reason, but whatever.

**Comment by axyjo** [comment]
Also, commit 86ee651a98eb060901ce is part of this.

**Comment by theXYZT** [comment]
Redundancy is a sign of emphasis.

**Comment by theXYZT** [comment]
I get to close it before you do.

**Comment by theXYZT** [comment]
Don't you dare reopen it.

**Comment by axyjo** [comment]
I let you close it.
